version: '3.8'

services:
  backend:
    environment:
      - CORS_ORIGIN=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://192.168.100.82:5173,http://192.168.100.82:5174,http://192.168.100.82:5175,http://192.168.100.82:5176

  frontend:
    environment:
      - VITE_API_URL=http://backend:3001
